#!/bin/bash

# Author : Diego Lago <diego.lago.gonzalez@hp.com>
# Version: 0.1
# Date   : 2015-05-11
# Home   : https://github.com/diegolagoglez/console-colors
# License: GPLv3 (See LICENSE)

colors=(black red green yellow blue purple cyan gray dark-gray light-red light-green light-yellow light-blue light-purple light-cyan white)

colors_abbrs=(k r g y b p c g dg lr lg ly lb lp lc w)

attrs=(normal bold dim underline strike inverted hidden)

attrs_abbrs=(n b d u s i h)

declare -A color_codes
declare -A color_attrs_codes

color_codes[black]="30"
color_codes[red]="31"
color_codes[green]="32"
color_codes[yellow]="33"
color_codes[blue]="34"
color_codes[purple]="35"
color_codes[cyan]="36"
color_codes[gray]="37"
color_codes[dark-gray]="90"
color_codes[light-red]="91"
color_codes[light-green]="92"
color_codes[light-yellow]="93"
color_codes[light-blue]="94"
color_codes[light-purple]="95"
color_codes[light-cyan]="96"
color_codes[white]="97"

color_codes[k]="30"
color_codes[r]="31"
color_codes[g]="32"
color_codes[y]="33"
color_codes[b]="34"
color_codes[p]="35"
color_codes[c]="36"
color_codes[gr]="37"
color_codes[dg]="90"
color_codes[lr]="91"
color_codes[lg]="92"
color_codes[ly]="93"
color_codes[lb]="94"
color_codes[lp]="95"
color_codes[lc]="96"
color_codes[w]="97"

color_codes[reset]="0"
color_codes[x]="0"

color_attrs_codes[normal]="0"
color_attrs_codes[bold]="1"
color_attrs_codes[dim]="2"
color_attrs_codes[underline]="4"
color_attrs_codes[strike]="9"
color_attrs_codes[inverted]="7"
color_attrs_codes[hidden]="8"

color_attrs_codes[n]="0"
color_attrs_codes[b]="1"
color_attrs_codes[d]="2"
color_attrs_codes[u]="4"
color_attrs_codes[s]="9"
color_attrs_codes[i]="7"
color_attrs_codes[h]="8"

CONSOLE_COLORS_ENABLE=1

function enable_colors() {
	CONSOLE_COLORS_ENABLE=1
}

function disable_colors() {
	CONSOLE_COLORS_ENABLE=0
}

function disable_colors_if_no_tty() {
	if [ ! -t 1 ]; then
		disable_colors
	fi
}

function get_color_attrs() {
	[ ! -z "$1" ] && [ ${color_attrs_codes[$1]+exists} ] && echo -n ${color_attrs_codes[$1]}
}

function color() {
	[ $CONSOLE_COLORS_ENABLE != 0 ] && [ ! -z "$1" ] && [ ${color_codes[$1]+exists} ] && echo -ne "\e[$(get_color_attrs $2);${color_codes[$1]}m"
}

function c() {
	color "$@"
}

function pcolor() {
	# There is no 'echo -e' (no escape character interpretation) because
	# that should be done by the prompt (PS1, PS2, PS3 and PS4).
	[ $CONSOLE_COLORS_ENABLE != 0 ] && [ ! -z "$1" ] && [ ${color_codes[$1]+exists} ] && echo -n "\[\e[$(get_color_attrs $2);${color_codes[$1]}m\]"
}

function pc() {
	pcolor "$@"
}

if [ $(basename -- $0) == "console-colors" ]; then
	echo "ERROR: Please, source this file instead of executing it." 1>&2 && exit 1
fi
